spring:
  jpa:
#    database: mysql
    database: h2
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

########### ?? DB ??(H2)####################
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
##############################################

logging:
  level:
    org:
      hibernate:
        type: trace