server:
  port: 9000
spring:
  jpa:
    database: mysql

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none

########### DB 설정####################
  profiles:
    include: aws
##############################################
logging:
  level:
    org:
      hibernate:
        type: trace